name: midterm
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  provider: ^6.1.1
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  connectivity_plus: ^5.0.2
  shared_preferences: ^2.2.2
  flutter_login_facebook: ^1.9.0
  google_sign_in: ^6.2.1
  pin_code_fields: ^8.0.1
  flutter_rating_bar: ^4.0.1
  intl: ^0.18.0
  permission_handler: ^11.1.0
  images_picker: ^1.2.11
  dio: ^5.4.0
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Raleway
      fonts: 
        - asset: assets/fonts/RalewayRomanBold.ttf
          weight: 700
        - asset: assets/fonts/RalewayBold.ttf
          weight: 700
        - asset: assets/fonts/RalewayMedium.ttf
          weight: 500
        - asset: assets/fonts/RalewaySemiBold.ttf
          weight: 600
        - asset: assets/fonts/RalewayRegular.ttf
          weight: 400
        - asset: assets/fonts/RalewayRomanMedium.ttf
          weight: 500
        - asset: assets/fonts/RalewayRomanRegular.ttf
          weight: 400
        - asset: assets/fonts/RalewayRomanSemiBold.ttf
          weight: 600
    - family: Inter
      fonts: 
        - asset: assets/fonts/InterSemiBold.ttf
          weight: 600
        - asset: assets/fonts/InterMedium.ttf
          weight: 500
